### ISSUE TITLE
Implement Training mode that does not apply reparameterization to be in line with MONAI Impl

### ISSUE THREAD

**Issue by masadcv** [kabbas570/Variational-AutoEncoder_Codes_PyTorch#1]
https://github.com/kabbas570/Variational-AutoEncoder_Codes_PyTorch/blob/f8d7417fc902a98998fdbdd911a5fb4a06ec17e2/models.py#L188

As we discussed briefly in the meeting, it would make sense to make this implementation in line with what MONAI has implemented. In particular, the only thing that you may need to change is to detect training mode/eval mode and then skip some steps for eval mode as we discussed. I believe this may help with the accurayc of the inference of the model as we dont want it to be random in the inference. 

Later, you can have some way to run the inference by selecting those mean/varaince yourself and seeing how the model ooutput transforms over the gaussian random variable space.

**Comment by kabbas570** [comment]
Yes, I have modified the reparameterize part; the modified  model and training loops are here

https://github.com/kabbas570/Variational-AutoEncoder_Codes_PyTorch/tree/main/models

**Comment by masadcv** [comment]
Ok I am closing now
